### PR TITLE
Disallow run as a root user

### PR DESCRIPTION
**Pull request by rockTA**

### CODE REVIEW

**Comment by leoluk** [comment]
What's the issue you're trying to solve?

**Comment by leoluk** [comment]
Either way, no reason not to merge it

**Comment by rockTA** [comment]
As described in my other pull request (https://github.com/leoluk/configmaster/pull/47), there were some issues because admins would run this as root. It has been suggested to implement a quick fix for this specific command.
In the future the user could be checked in other places too - but I don't know if it's worth the effort?

**Comment by leoluk** [comment]
Fine as a quick fix, but keep in mind that this will still load much of the Django framework code as root.

**Pull request merged**
