### PR TITLE
Default settings: Mark CSRF and session cookies as secure

### PR DESCRIPTION
**Pull request by Alexander-N**

### CODE REVIEW

**Comment by leoluk** [comment]
I fully agree with having safe defaults, but if this break a default development setup it needs to be documented. Should be fine for development on OpenShift since that uses SSL by default anyway.

**Comment by Alexander-N** [comment]
Just pushed another option, how about setting them explicitly when `DEBUG` is `False`? This way we ensure that they are not forgotten in production and we don't need to configure them for development environments.

**Comment by leoluk** [comment]
That's a good solution, I'll mark this approved. Unless you need this urgently merged, I'l address the remaining PRs first to avoid the need to rebase them all.

**Comment by Alexander-N** [comment]
Not urgent at all, since it's only the default.

**Pull request merged**
